### ISSUE TITLE
Crash when running on real device

### ISSUE THREAD

**Issue by MattMasters** [mapbox/vision-ios-examples#60]
Hi, I'm trying to run the app on an iPhoneXs and have ran into an issue after launching the app; It renders the menu, then crashes. Looking at the console on xcode this is the error:

`2019-04-26 16:33:07.642546+0100 demo[9530:2163758] [coreml] Error evaluating Core ML custom layer "ArgmaxCustomLayer" on CPU.
2019-04-26 16:33:07.642697+0100 demo[9530:2163758] [coreml] Error in computing user-provided custom layer during neural network evaluation.
2019-04-26 16:33:07.643572+0100 demo[9530:2163758] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
*** First throw call stack:
(0x1add27758 0x1acf2fd00 0x1adc9edb0 0x1adc21cb4 0x10913eb88 0x10913a0cc 0x1090c8f2c 0x109131ebc 0x1ad931920 0x1ad93187c 0x1ad939dcc)
libc++abi.dylib: terminating with uncaught exception of type NSException`

Do you have any suggestions that I could try to resolve this?

Thanks,
Matt

**Comment by vladzima** [comment]
Working on it, will provide hotfix asap.

**Comment by chezzdev** [comment]
@MattMasters thanks for reporting the issue. It was fixed in `MapboxVisionNative` 0.3.1.
`master` branch of this repo already contains the fix.

**Comment by kaustubh-seachange** [comment]
This issue still persists in MapboxVisionNative pod version 0.4.0
